[general]
autofill=yes
shared_lastcall=yes

[sales]
strategy=rrmemory
timeout=20
retry=5
wrapuptime=10
maxlen=25
musicclass=default

[operations]
strategy=leastrecent
timeout=20
retry=5
wrapuptime=10
maxlen=25
musicclass=default
