import { registerRootComponent } from 'expo';

// Android killed-state FCM delivery is owned by the native
// AppFirebaseMessagingService generated by withTelnyxVoip.
registerRootComponent(require('./App').default);
