import { Copy, KeyRound, ShieldCheck, Trash2, X } from "lucide-react";
import { Status, PageHeader, Empty } from '../components/ui.jsx';

export function DeveloperPage({ data, revealedToken, onCreate, onRevoke, onClearToken }) {
  return <div className="page"><PageHeader eyebrow="PROGRAMMABLE TELECOM" title="Developer API" subtitle="Tenant-scoped APIs for calls, extensions, numbers and events."><button className="primary" onClick={onCreate}><KeyRound /> Create API key</button></PageHeader>
    {revealedToken && <section className="band"><div className="section-title"><div><h2>New API key</h2><p>This secret is shown once. Store it in a password manager or server environment.</p></div><button className="icon-button" title="Dismiss" onClick={onClearToken}><X /></button></div><div className="info-strip"><code>{revealedToken}</code><button className="secondary" onClick={() => navigator.clipboard.writeText(revealedToken)}><Copy /> Copy</button></div></section>}
    <section className="band"><div className="section-title"><div><h2>API keys</h2><p>Keys are isolated to the active organization and can be revoked immediately.</p></div></div>{data?.length ? <div className="object-list">{data.map((item) => <div key={item.id}><span className="object-icon"><KeyRound /></span><div><strong>{item.name}</strong><small>{item.prefix}... · {item.scopes.join(', ')}</small></div><Status good={!item.revokedAt}>{item.revokedAt ? 'Revoked' : 'Active'}</Status>{!item.revokedAt && <button className="danger icon-button" title="Revoke API key" onClick={() => onRevoke(item)}><Trash2 /></button>}</div>)}</div> : <Empty icon={KeyRound} title="No API keys" copy="Create a scoped key for a trusted server integration." />}</section>
    <section className="band"><div className="section-title"><div><h2>Core endpoints</h2><p>Send the key as <code>Authorization: Bearer vcp_live_...</code>. Responses are JSON.</p></div></div><div className="detail-grid"><div><span>Service health</span><code>GET /api/platform/health</code></div><div><span>Organization extensions</span><code>GET /api/platform/extensions</code></div><div><span>Active calls / dial</span><code>GET · POST /api/platform/calls</code></div><div><span>Call action</span><code>PATCH /api/platform/calls</code></div><div><span>Inventory / purchase</span><code>GET · POST /api/platform/numbers</code></div><div><span>Call events</span><code>GET /api/platform/events</code></div></div><div className="info-strip"><ShieldCheck /><span>Public phone-number purchases require <code>confirmPurchase: true</code>. PSTN transport and regulated numbering remain on Telnyx while Vocivo owns authentication, tenancy, routing policy and the API surface.</span></div></section>
  </div>;
}
