import { Activity, BellRing, Building2, Plus, ShieldCheck } from "lucide-react";
import { Status, PageHeader } from '../components/ui.jsx';

export function PlatformDashboard({ data, onOpenCustomers, onOpenSubscriptions }) {
  const metrics = data?.platform || {};
  const attention = (data?.organizations || []).filter((item) => item.status !== 'active' || !['active', 'trialing'].includes(item.subscription.status));
  return <div className="page"><PageHeader eyebrow="VOCIVO COMMUNICATIONS CONTROL PLANE" title="Platform overview" subtitle="Customers, recurring subscriptions and service health owned and operated by Vocivo Communications."><button className="primary" onClick={onOpenCustomers}><Plus /> Add customer</button></PageHeader>
    <div className="metrics platform-metrics"><div><Building2 /><span>Customer accounts</span><strong>{metrics.customers || 0}</strong><small>{metrics.activeSubscriptions || 0} active subscriptions</small></div><div><Activity /><span>Provisioned users</span><strong>{metrics.seats || 0}</strong><small>Across all tenants</small></div><div><BellRing /><span>Monthly recurring revenue</span><strong>{metrics.currency || 'USD'} {Number(metrics.monthlyRecurringRevenue || 0).toLocaleString()}</strong><small>{metrics.trials || 0} customer trials</small></div><div><ShieldCheck /><span>Needs attention</span><strong>{metrics.attention || 0}</strong><small>Past due or suspended</small></div></div>
    <section className="band"><div className="section-title"><div><h2>Platform ownership</h2><p>This identity is separate from every customer company and company administrator.</p></div><Status good>Platform owner</Status></div><div className="detail-grid"><div><span>Platform owner</span><strong>{metrics.owner || 'Vocivo Communications'}</strong></div><div><span>Account layer</span><strong>Vocivo superadmin</strong></div><div><span>Customer isolation</span><strong>Company-specific admins and users</strong></div><div><span>Selected customer</span><strong>Never grants platform ownership</strong></div></div></section>
    <section className="band"><div className="section-title"><div><h2>Customer portfolio</h2><p>Subscription state, plan capacity and company administrator coverage.</p></div><button className="text-button" onClick={onOpenCustomers}>View customers</button></div><div className="portfolio-list">{(data?.organizations || []).slice(0, 8).map((item) => <div key={item.id}><span className="company-monogram">{item.name.charAt(0)}</span><div><strong>{item.name}</strong><small>{item.admins.length ? `${item.admins[0].name} · ${item.admins[0].email}` : 'Company administrator not configured'}</small></div><span>{item.plan.name}<small>{item.usage.seats}/{item.plan.limits.seats} users</small></span><Status good={item.subscription.status === 'active'} warn={item.subscription.status === 'trialing'}>{item.subscription.status}</Status></div>)}</div></section>
    {attention.length > 0 && <section className="band"><div className="section-title"><div><h2>Action required</h2><p>Customer accounts that cannot use all assigned services.</p></div><button className="secondary" onClick={onOpenSubscriptions}>Review subscriptions</button></div><div className="readiness">{attention.map((item) => <div key={item.id}><span>{item.name}</span><strong>{item.subscription.status.replaceAll('_', ' ')}</strong><Status warn>Review</Status></div>)}</div></section>}
  </div>;
}
