import { useState } from "react";
import { Save } from "lucide-react";
import { Status, PageHeader } from '../components/ui.jsx';

export function SubscriptionsPage({ data, onSave, busy }) {
  const [drafts, setDrafts] = useState({});
  const value = (item) => drafts[item.id] || item.subscription;
  const change = (item, patch) => setDrafts((current) => ({ ...current, [item.id]: { ...value(item), ...patch } }));
  return <div className="page"><PageHeader eyebrow="BILLING OPERATIONS" title="Subscriptions" subtitle="Plans, renewal state, limits and commercial status for every Vocivo customer." />
    <div className="plan-grid">{(data?.plans || []).map((plan) => <section key={plan.id}><div><span>{plan.name}</span><strong>{plan.currency} {plan.monthlyPrice}<small>/month</small></strong><p>{plan.description}</p></div><div className="plan-limits"><span>{plan.limits.seats} users</span><span>{plan.limits.phoneNumbers} numbers</span><span>{plan.limits.concurrentCalls} concurrent calls</span></div><Status good={plan.active}>{plan.active ? 'Available' : 'Retired'}</Status></section>)}</div>
    <section className="band"><div className="section-title"><div><h2>Customer subscriptions</h2><p>Only active and trialing subscriptions can use customer services.</p></div></div><div className="table-shell"><table><thead><tr><th>Customer</th><th>Plan</th><th>Status</th><th>Billing</th><th>Amount</th><th>Renews</th><th /></tr></thead><tbody>{(data?.organizations || []).map((item) => { const draft = value(item); return <tr key={item.id}><td><strong>{item.name}</strong><small>{item.usage.seats} active users</small></td><td><select value={draft.planId} onChange={(e) => change(item, { planId: e.target.value })}>{data.plans.map((plan) => <option key={plan.id} value={plan.id}>{plan.name}</option>)}</select></td><td><select value={draft.status} onChange={(e) => change(item, { status: e.target.value })}><option value="trialing">Trialing</option><option value="active">Active</option><option value="past_due">Past due</option><option value="suspended">Suspended</option><option value="canceled">Canceled</option></select></td><td><select value={draft.billingCycle} onChange={(e) => change(item, { billingCycle: e.target.value })}><option value="monthly">Monthly</option><option value="annual">Annual</option><option value="custom">Custom</option></select></td><td><input type="number" min="0" step="0.01" value={draft.amount} onChange={(e) => change(item, { amount: Number(e.target.value) })} /></td><td>{draft.renewsAt ? new Date(draft.renewsAt).toLocaleDateString() : 'Not scheduled'}</td><td><button className="secondary" disabled={busy || !drafts[item.id]} onClick={async () => { if (await onSave(item.id, draft)) setDrafts((current) => { const next = { ...current }; delete next[item.id]; return next; }); }}><Save /> Save</button></td></tr>; })}</tbody></table></div></section>
  </div>;
}
