import { Plus, Route, Save, Trash2 } from "lucide-react";
import { uid } from '../configuration.js';
import { Toggle, PageHeader } from '../components/ui.jsx';

export function OutboundPage({ config, setConfig, onSave }) {
  const add = () => setConfig({ ...config, outboundRules: [...config.outboundRules, { id: uid('rule'), name: 'New outbound rule', prefix: '', extensionRange: '', numberLength: '', department: 'All', routes: ['Vocivo Managed'], enabled: true }] });
  const update = (id, patch) => setConfig({ ...config, outboundRules: config.outboundRules.map((x) => x.id === id ? { ...x, ...patch } : x) });
  return <div className="page"><PageHeader eyebrow="CALL ROUTING" title="Outbound rules" subtitle="Prioritized patterns determine how users reach public destinations."><button className="secondary" onClick={add}><Plus /> Add rule</button><button className="primary" onClick={onSave}><Save /> Save rules</button></PageHeader><div className="table-shell"><table><thead><tr><th>#</th><th>Rule</th><th>Prefix</th><th>Extensions</th><th>Length</th><th>Department</th><th>Route</th><th>Enabled</th><th /></tr></thead><tbody>{config.outboundRules.map((rule, index) => <tr key={rule.id}><td><strong>{index + 1}</strong></td><td><input value={rule.name} onChange={(e) => update(rule.id, { name: e.target.value })} /></td><td><input value={rule.prefix} onChange={(e) => update(rule.id, { prefix: e.target.value })} /></td><td><input value={rule.extensionRange} onChange={(e) => update(rule.id, { extensionRange: e.target.value })} placeholder="All" /></td><td><input value={rule.numberLength} onChange={(e) => update(rule.id, { numberLength: e.target.value })} placeholder="Any" /></td><td><input value={rule.department} onChange={(e) => update(rule.id, { department: e.target.value })} /></td><td><strong>{rule.routes[0] === 'Vocivo Telnyx' ? 'Vocivo Managed' : rule.routes[0] || 'Vocivo Managed'}</strong></td><td><Toggle value={rule.enabled} onChange={(enabled) => update(rule.id, { enabled })} /></td><td><button className="danger icon-button" onClick={() => setConfig({ ...config, outboundRules: config.outboundRules.filter((x) => x.id !== rule.id) })}><Trash2 /></button></td></tr>)}</tbody></table></div><div className="info-strip"><Route /><span>Rules are evaluated from top to bottom and authorized calls use the managed Vocivo carrier connection.</span></div></div>;
}
