import { BellRing, ContactRound, LogOut, Mic, PhoneIncoming, Wifi, WifiOff } from "lucide-react";
import { VerifiedNumbersPanel } from '../numbers/VerifiedNumbersPanel.jsx';

export function SettingsView({ profile, ownedNumbers, verifiedNumbers, voice, verification, onLogout }) {
  return (
    <section className="content-view settings-view">
      <header className="workspace-header"><div><p className="eyebrow">ACCOUNT</p><h1>Phone settings</h1></div></header>
      <div className="settings-section"><h2>Connection</h2><div className="setting-row"><span className={voice.ready ? 'setting-icon good' : 'setting-icon'}>{voice.ready ? <Wifi /> : <WifiOff />}</span><div><strong>Vocivo web phone</strong><small>{voice.statusLabel}</small></div><span className={voice.ready ? 'state good' : 'state'}>{voice.ready ? 'Connected' : 'Waiting'}</span></div><div className="setting-row"><span className="setting-icon"><Mic /></span><div><strong>Microphone</strong><small>Your browser will ask before sharing audio.</small></div><span className="state">Browser managed</span></div><div className="setting-row"><span className="setting-icon"><BellRing /></span><div><strong>Browser call alerts</strong><small>Play a ringtone, vibrate and show incoming-call notifications while Vocivo is open.</small></div><button className="logout-button" disabled={voice.notificationPermission === 'granted'} onClick={() => voice.enableBrowserAlerts()}>{voice.notificationPermission === 'granted' ? 'Enabled' : voice.notificationPermission === 'denied' ? 'Blocked' : 'Enable'}</button></div></div>
      <div className="settings-section"><div className="section-heading"><div><h2>Incoming Vocivo numbers</h2><p>Calls to these assigned numbers ring Vocivo while the web phone is connected.</p></div></div>{ownedNumbers.map((number) => <div className="setting-row" key={number.id}><span className="setting-icon"><PhoneIncoming /></span><div><strong>{number.phone_number}</strong><small>{number.label}</small></div><span className={number.receives_calls ? 'state good' : 'state'}>{number.receives_calls ? 'Incoming enabled' : 'Needs routing'}</span></div>)}</div>
      <VerifiedNumbersPanel numbers={verifiedNumbers} pending={verification.pending} busy={verification.busy} error={verification.error} onRequest={verification.request} onVerify={verification.verify} onRemove={verification.remove} onCancel={verification.cancel} />
      <div className="settings-section"><h2>Profile</h2><div className="setting-row">{profile.photo_url ? <img className="settings-avatar" src={profile.photo_url} alt={profile.full_name} /> : <span className="setting-icon"><ContactRound /></span>}<div><strong>{profile.full_name}</strong><small>{profile.job_title || profile.department || profile.email}</small><small>{[profile.mobile, profile.location].filter(Boolean).join(' · ')}</small></div><button className="logout-button" onClick={onLogout}><LogOut size={16} /> Sign out</button></div></div>
    </section>
  );
}
