import { useState } from "react";
import { CalendarClock, Headphones, LockKeyhole, PhoneForwarded, QrCode as QrCodeIcon, PhoneIncoming, Save, Smartphone, Users, Voicemail } from "lucide-react";
import { Status, Toggle, Field, Modal } from '../components/ui.jsx';

import { UserNumbers } from './UserNumbers.jsx';

export const userTabs = [['general', Users, 'General'], ['numbers', PhoneIncoming, 'Numbers'], ['provision', QrCodeIcon, 'Provisioning'], ['forward', PhoneForwarded, 'Call forwarding'], ['schedule', CalendarClock, 'Schedule'], ['devices', Smartphone, 'Devices'], ['voicemail', Voicemail, 'Voicemail'], ['permissions', LockKeyhole, 'Permissions']];

export function UserEditor({ draft, profile, organization, api, onNumbersSaved, onDraft, onProfile, onClose, onSave, onProvision, busy }) {
  const [tab, setTab] = useState('general');
  const permissions = { international: 'International outbound calling', transfer: 'Transfer and attended transfer', video: 'Video calling', reports: 'View call reports' };
  return <Modal wide title={draft.id ? `Edit ${draft.name}` : 'Add user'} subtitle={draft.id ? `Extension ${draft.extension}` : 'Create identity, extension and app access'} onClose={onClose}>
    <form className="user-editor" onSubmit={event => { if (tab === 'numbers' && draft.id) event.preventDefault(); else onSave(event); }}><nav className="editor-tabs">{userTabs.map(([id, Icon, label]) => <button type="button" key={id} className={tab === id ? 'active' : ''} onClick={() => setTab(id)}><Icon />{label}</button>)}</nav><div className="editor-body">
      {tab === 'general' && <div className="form-grid"><Field label={organization?.accountType === 'individual' ? 'Service identity' : 'Extension'} help={draft.id ? 'Changing this identity can affect saved contacts.' : `Leave blank to assign the next available slot in ${organization?.extensionStart || 2000}-${organization?.extensionEnd || 2019}.`}><input autoFocus value={draft.extension} onChange={(e) => onDraft({ ...draft, extension: e.target.value.replace(/\D/g, '').slice(0, 5) })} placeholder="Auto assign" /></Field><Field label="Role"><select aria-label="Role" value={organization?.accountType === 'individual' ? 'individual' : draft.role} disabled={organization?.accountType === 'individual'} onChange={(e) => onDraft({ ...draft, role: e.target.value })}>{organization?.accountType === 'individual' ? <option value="individual">Individual account</option> : <><option value="user">Employee</option><option value="manager">Manager</option><option value="company_admin">Company administrator</option><option value="company_owner">Company owner</option></>}</select></Field><Field label="Display name"><input value={draft.name} onChange={(e) => onDraft({ ...draft, name: e.target.value })} required /></Field><Field label="Email"><input type="email" value={draft.email} onChange={(e) => onDraft({ ...draft, email: e.target.value })} /></Field>{organization?.accountType !== 'individual' && <Field label={draft.id ? 'Reset web sign-in password' : 'Temporary web sign-in password'} help={draft.id ? 'Leave blank to keep existing access. Set a password to enable web sign-in for a QR-only user.' : 'Sign in at vocivo.app with this email and password. Use 10 characters with upper and lowercase letters and a number. The user must change it at first sign-in.'}><input type="password" autoComplete="new-password" required={!draft.id} value={draft.loginPassword || ''} onChange={(e) => onDraft({ ...draft, loginPassword: e.target.value })} /></Field>}<Field label="Mobile"><input value={draft.mobile} onChange={(e) => onDraft({ ...draft, mobile: e.target.value })} placeholder="+966..." /></Field><Field label="Department"><input value={draft.department} onChange={(e) => onDraft({ ...draft, department: e.target.value })} disabled={organization?.accountType === 'individual'} /></Field></div>}
      {tab === 'numbers' && (draft.id ? <UserNumbers user={draft} organizationId={organization?.id} api={api} onSaved={onNumbersSaved} /> : <Status warn>Save the user before assigning numbers</Status>)}
      {tab === 'provision' && <div className="provision-panel"><QrCodeIcon /><h3>Mobile app provisioning</h3><p>Generate a ten-minute QR code that securely enrolls this user without displaying the SIP password.</p>{draft.id ? <button type="button" className="primary" onClick={() => onProvision(draft)}><QrCodeIcon /> Generate setup QR</button> : <Status warn>Save the user first</Status>}</div>}
      {tab === 'forward' && <div className="form-grid"><Field label="No-answer timeout"><div className="suffix-input"><input type="number" min="10" max="120" value={profile.noAnswerSeconds} onChange={(e) => onProfile({ ...profile, noAnswerSeconds: Number(e.target.value) })} /><span>seconds</span></div></Field><Field label="Simultaneous ring"><input value={profile.simultaneousRing} onChange={(e) => onProfile({ ...profile, simultaneousRing: e.target.value })} placeholder="Extension or E.164 number" /></Field><Field label="When busy"><input value={profile.forwardBusy} onChange={(e) => onProfile({ ...profile, forwardBusy: e.target.value })} placeholder="Voicemail, extension or number" /></Field><Field label="When unanswered"><input value={profile.forwardNoAnswer} onChange={(e) => onProfile({ ...profile, forwardNoAnswer: e.target.value })} /></Field><Field label="When unavailable" wide><input value={profile.forwardUnavailable} onChange={(e) => onProfile({ ...profile, forwardUnavailable: e.target.value })} /></Field></div>}
      {tab === 'schedule' && <div className="form-grid"><Field label="Routing schedule" wide><select value={profile.schedule === 'Always available' ? 'Always available' : 'Use office hours'} onChange={(e) => onProfile({ ...profile, schedule: e.target.value })}><option>Use office hours</option><option>Always available</option></select></Field><div className="info-strip wide"><CalendarClock /><span>Office hours and holidays are managed centrally.</span></div></div>}
      {tab === 'devices' && <div className="device-list"><div><Smartphone /><div><strong>Vocivo iOS app</strong><span>{draft.id ? 'Ready for QR enrollment or reset' : 'Available after creation'}</span></div><Status good={Boolean(draft.id)}>{draft.id ? 'Provisionable' : 'Pending'}</Status></div><div><Headphones /><div><strong>SIP desk phone or softphone</strong><span>Secure registration through the Vocivo voice service</span></div><Status good={Boolean(draft.sipUsername)}>{draft.sipUsername ? 'Credential issued' : 'Pending'}</Status></div></div>}
      {tab === 'voicemail' && <div className="setting-line"><div><strong>Enable voicemail</strong><span>Answer calls when the user cannot.</span></div><Toggle value={profile.voicemailEnabled} onChange={(voicemailEnabled) => onProfile({ ...profile, voicemailEnabled })} /></div>}
      {tab === 'permissions' && <div className="permission-list">{Object.entries(permissions).map(([key, label]) => <div className="setting-line" key={key}><div><strong>{label}</strong><span>Applied to extension {draft.extension || 'after creation'}.</span></div><Toggle value={profile.permissions[key]} onChange={(value) => onProfile({ ...profile, permissions: { ...profile.permissions, [key]: value } })} /></div>)}</div>}
    </div><footer><button type="button" className="secondary" onClick={onClose}>{tab === 'numbers' ? 'Close' : 'Cancel'}</button>{(tab !== 'numbers' || !draft.id) && <button className="primary" disabled={busy}><Save /> Save user</button>}</footer></form>
  </Modal>;
}
