import { useMemo, useState } from "react";
import { Download, PhoneCall, QrCode as QrCodeIcon, Search, Trash2, UserRoundPlus, Users } from "lucide-react";
import { Status, PageHeader, Empty } from '../components/ui.jsx';

export function UsersPage({ items, onAdd, onEdit, onDelete, onProvision, onExport }) {
  const [query, setQuery] = useState(''); const [selected, setSelected] = useState([]);
  const filtered = useMemo(() => items.filter((x) => `${x.extension} ${x.name} ${x.department} ${x.email}`.toLowerCase().includes(query.toLowerCase())), [items, query]);
  return <div className="page"><PageHeader eyebrow="PEOPLE" title="Users" subtitle="Identity, extension, routing, devices, voicemail and permissions."><button className="secondary" onClick={onExport}><Download /> Export</button><button className="primary" onClick={onAdd}><UserRoundPlus /> Add user</button></PageHeader><div className="toolbar"><label><Search /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search name, extension, department or email" /></label><span>{selected.length ? `${selected.length} selected` : `${filtered.length} users`}</span></div><div className="table-shell"><table><thead><tr><th><input type="checkbox" checked={filtered.length > 0 && selected.length === filtered.length} onChange={(e) => setSelected(e.target.checked ? filtered.map((x) => x.id) : [])} /></th><th>User</th><th>Extension</th><th>Department</th><th>Role</th><th>App setup</th><th>Status</th><th /></tr></thead><tbody>{filtered.map((item) => <tr key={item.id}><td><input type="checkbox" checked={selected.includes(item.id)} onChange={(e) => setSelected(e.target.checked ? [...selected, item.id] : selected.filter((id) => id !== item.id))} /></td><td><strong>{item.name}</strong><small>{item.email || item.mobile || 'No contact detail'}</small></td><td><button className="extension" onClick={() => onEdit(item)}>{item.extension}</button></td><td>{item.department}</td><td><span className="role">{item.role}</span></td><td><button className="qr-action" onClick={() => onProvision(item)}><QrCodeIcon /> Setup QR</button></td><td><Status good={item.status === 'active'}>{item.status}</Status></td><td><div className="row-actions"><button onClick={() => onEdit(item)}>Edit</button><button className="danger" onClick={() => onDelete(item)}><Trash2 /></button></div></td></tr>)}</tbody></table>{!filtered.length && <Empty icon={Users} title="No users found" copy="Create a user or change the current search." />}</div><div className="info-strip"><PhoneCall /><span>Calls between registered Vocivo extensions use internal SIP routing and do not consume public PSTN minutes.</span></div></div>;
}
